In [ ]:
#low level API tensorflow: TensorFlow Core.
# Dictionnary: 
# Tensorflow Program: tf.Graph
# Tensorflow runtime: tf.Session
#components: datasets, layers, feature_columns

In [2]:
import numpy as np
import tensorflow as tf

# tensor: values shaped into an array of any dimensions
# tensor's rank: nb of dimensions
# tensor's shape: tuple of integers for array's length along each Dimension!!

3. # rank:0,shape []
[1,2,3] # rank:1, shape[3]
[[1,2,3],[4,5,6]] # rank:2, shape[2,3]
[[[1,2,3]],[[7,8,9]]] # rank:3, shape[2,1,3]

[[[1, 2, 3]], [[7, 8, 9]]]

In [3]:
#Graph: 
#1) tf.Operation("Ops"): nodes of graph -> describes operations to process
#2) tf.tensors: edges of graph. values that'll flow through the graph
# ici on construit juste le graph: 
a = tf.constant(3.0,dtype=tf.float32)
b = tf.constant(4.0) # by default tf.float32

total= a + b 

print(a)
print(b)
print(a+b)

Tensor("Const:0", shape=(), dtype=float32)
Tensor("Const_1:0", shape=(), dtype=float32)
Tensor("add_1:0", shape=(), dtype=float32)


In [4]:
#TensorBoard: 
# save the computation graph --> tensorBoard summary file:
writer = tf.summary.FileWriter('.')
writer.add_graph(tf.get_default_graph())
writer.flush()
#Generation of event: events.out.tfevents.{timestamp}.{hostname}

In [1]:
# Dans un terminal nouveau: 
 tensorboard --logdir .
# ouvrons la page web: 
http://localhost:6006/#graphs&run=.
# on peut voir le graph

IndentationError: unexpected indent (<ipython-input-1-39b6f4ae501e>, line 2)

In [23]:
# Session:
# tf.Graph: like a .py file
# tf.Session: like python Executable: Encapsulates the state of tensorflow runtime (run Tensorflow operations)

sess=tf.Session()
sess.run(total)

7.0

In [8]:
sess.run({'a,b':(a,b), 'total': total})

{'a,b': (3.0, 4.0), 'total': 7.0}

In [16]:
# During a call of tf.Session.run, any tf.Tensor only has a single value.
vec=tf.random_uniform(shape=(3,))
out1 = vec + 1
out2 = vec + 2 
print(sess.run(vec))
print(sess.run(vec))
print(sess.run((out1,out2)))# 1! invocation de vec, la meme pour les out_i

[0.35443807 0.0322957  0.79917777]
[0.65402114 0.08679318 0.76199937]
(array([1.7263842, 1.8025925, 1.8210615], dtype=float32), array([2.7263842, 2.8025925, 2.8210616], dtype=float32))


In [28]:
# Feeding: 
#Placeholder: promise to provide a value later(comme function argument)

x=tf.placeholder(tf.float32)
y=tf.placeholder(tf.float32)
z=x+y
# running to evaluate: 
print(sess.run(z,feed_dict={x:3,y:4.5}))
print(sess.run(z,feed_dict={x:[1 ,3],y:[2 ,4]}))

7.5
[3. 7.]


In [ ]:
# DataSets: 